version: "3.7"
services:
  backend:
    container_name: uniswap-project-backend
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    environment:
      FLASK_ENV: development
  frontend:
    container_name: uniswap-project-frontend
    build: ./frontend
    volumes:
      - './frontend:/frontend'
      - '/frontend/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run start
    depends_on:
      - backend
